# Use the official OpenJDK base image
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container
COPY account.cmd-1.0.0.jar /app/

# Command to run the application
CMD ["java", "-jar", "your-app.jar"]
